// <auto-generated />
using System;
using AspNetSerwer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetSerwer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetSerwer.Data.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b97091f-a099-4ce0-9084-cd37976a2db7"),
                            Content = "This is post 1 and has some interesting content",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = new Guid("f5aa1bfb-b5a8-493c-a579-7dac454e8ee1"),
                            Content = "This is post 2 and has some interesting content",
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = new Guid("a82b6814-6749-495b-9ed9-bd121085f053"),
                            Content = "This is post 3 and has some interesting content",
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = new Guid("2581c5af-5a4c-470c-8e9d-f4e21ddb9b93"),
                            Content = "This is post 4 and has some interesting content",
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = new Guid("ce17d3f7-7509-4b72-96bd-87d3d44323dd"),
                            Content = "This is post 5 and has some interesting content",
                            Title = "Post 5"
                        },
                        new
                        {
                            Id = new Guid("c82ab38b-24e8-4d5e-a7ae-f1bf16e195e3"),
                            Content = "This is post 6 and has some interesting content",
                            Title = "Post 6"
                        },
                        new
                        {
                            Id = new Guid("65d2e60c-7cd4-4af3-8669-7678e26eff1a"),
                            Content = "This is post 7 and has some interesting content",
                            Title = "Post 7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
